// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tranquildata/config (interfaces: NamingScheme,Provider,Postprocessor)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_definition_types.go -package=mocks github.com/tranquildata/config NamingScheme,Provider,Postprocessor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNamingScheme is a mock of NamingScheme interface.
type MockNamingScheme struct {
	ctrl     *gomock.Controller
	recorder *MockNamingSchemeMockRecorder
	isgomock struct{}
}

// MockNamingSchemeMockRecorder is the mock recorder for MockNamingScheme.
type MockNamingSchemeMockRecorder struct {
	mock *MockNamingScheme
}

// NewMockNamingScheme creates a new mock instance.
func NewMockNamingScheme(ctrl *gomock.Controller) *MockNamingScheme {
	mock := &MockNamingScheme{ctrl: ctrl}
	mock.recorder = &MockNamingSchemeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNamingScheme) EXPECT() *MockNamingSchemeMockRecorder {
	return m.recorder
}

// Components mocks base method.
func (m *MockNamingScheme) Components(propertyName string) []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Components", propertyName)
	ret0, _ := ret[0].([]string)
	return ret0
}

// Components indicates an expected call of Components.
func (mr *MockNamingSchemeMockRecorder) Components(propertyName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Components", reflect.TypeOf((*MockNamingScheme)(nil).Components), propertyName)
}

// Compose mocks base method.
func (m *MockNamingScheme) Compose(components []string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compose", components)
	ret0, _ := ret[0].(string)
	return ret0
}

// Compose indicates an expected call of Compose.
func (mr *MockNamingSchemeMockRecorder) Compose(components any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compose", reflect.TypeOf((*MockNamingScheme)(nil).Compose), components)
}

// Validate mocks base method.
func (m *MockNamingScheme) Validate(propertyName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", propertyName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockNamingSchemeMockRecorder) Validate(propertyName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockNamingScheme)(nil).Validate), propertyName)
}

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// KnownProperties mocks base method.
func (m *MockProvider) KnownProperties() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KnownProperties")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// KnownProperties indicates an expected call of KnownProperties.
func (mr *MockProviderMockRecorder) KnownProperties() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KnownProperties", reflect.TypeOf((*MockProvider)(nil).KnownProperties))
}

// Value mocks base method.
func (m *MockProvider) Value(propertyName string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value", propertyName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Value indicates an expected call of Value.
func (mr *MockProviderMockRecorder) Value(propertyName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockProvider)(nil).Value), propertyName)
}

// MockPostprocessor is a mock of Postprocessor interface.
type MockPostprocessor struct {
	ctrl     *gomock.Controller
	recorder *MockPostprocessorMockRecorder
	isgomock struct{}
}

// MockPostprocessorMockRecorder is the mock recorder for MockPostprocessor.
type MockPostprocessorMockRecorder struct {
	mock *MockPostprocessor
}

// NewMockPostprocessor creates a new mock instance.
func NewMockPostprocessor(ctrl *gomock.Controller) *MockPostprocessor {
	mock := &MockPostprocessor{ctrl: ctrl}
	mock.recorder = &MockPostprocessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostprocessor) EXPECT() *MockPostprocessorMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockPostprocessor) Process() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process")
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockPostprocessorMockRecorder) Process() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockPostprocessor)(nil).Process))
}
